(()=>{
  const KEY='cp-events';
  let events=[];
  try{events=JSON.parse(localStorage.getItem(KEY)||'[]')||[]}catch(e){events=[]}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const today=()=>{let d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
  function save(){localStorage.setItem(KEY,JSON.stringify(events));renderEventsHome()}
  function eventForm(){return '<div id="eventForm" style="display:none;margin-top:16px;text-align:left;background:#f8fafc;border:1px solid #e4e7ec;border-radius:14px;padding:14px"><h3 style="margin:0 0 12px">Nuevo evento</h3><label style="font-size:12px;font-weight:800">Nombre / activación</label><input id="evName" placeholder="Ej. Degustación Parrilla Fest" style="width:100%;padding:10px;margin:5px 0 10px;border:1px solid #d0d5dd;border-radius:9px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:9px"><div><label style="font-size:12px;font-weight:800">Fecha inicio</label><input id="evStart" type="date" value="'+today()+'" style="width:100%;padding:10px;margin-top:5px;border:1px solid #d0d5dd;border-radius:9px"></div><div><label style="font-size:12px;font-weight:800">Fecha fin</label><input id="evEnd" type="date" value="'+today()+'" style="width:100%;padding:10px;margin-top:5px;border:1px solid #d0d5dd;border-radius:9px"></div></div><label style="display:block;font-size:12px;font-weight:800;margin-top:10px">Marca</label><input id="evBrand" placeholder="Marca" style="width:100%;padding:10px;margin:5px 0 10px;border:1px solid #d0d5dd;border-radius:9px"><label style="font-size:12px;font-weight:800">Local / lugar</label><input id="evPlace" placeholder="Local o lugar del evento" style="width:100%;padding:10px;margin:5px 0 12px;border:1px solid #d0d5dd;border-radius:9px"><div style="display:flex;gap:8px"><button type="button" onclick="closeEventForm()" style="flex:1;padding:10px;border:1px solid #d0d5dd;border-radius:9px;background:#fff;font-weight:800">Cancelar</button><button type="button" onclick="saveBasicEvent()" style="flex:1;padding:10px;border:0;border-radius:9px;background:#2563eb;color:#fff;font-weight:800">Guardar evento</button></div></div>'}
  function renderCards(){if(!events.length)return '<div class="eventsEmpty"><div class="eventsIcon">📅</div><strong>Aún no hay eventos registrados</strong><div class="muted">Crea el primer evento para comenzar su planificación.</div></div>';return '<div style="margin-top:16px;text-align:left">'+events.slice().sort((a,b)=>a.start.localeCompare(b.start)).map(e=>'<div style="background:#fff;border:1px solid #e4e7ec;border-radius:13px;padding:13px;margin:8px 0"><div style="font-weight:850">'+esc(e.name)+'</div><div class="muted" style="margin-top:5px">📅 '+esc(e.start)+(e.end&&e.end!==e.start?' → '+esc(e.end):'')+'</div><div style="font-size:12px;margin-top:6px">🏷️ '+esc(e.brand)+' &nbsp; · &nbsp; 📍 '+esc(e.place)+'</div></div>').join('')+'</div>'}
  function renderEventsHome(){const box=document.getElementById('eventsModule');if(!box)return;box.innerHTML='<div class="eventsHead"><div><h2>Eventos</h2><div class="muted">Planificación de activaciones, personal y materiales.</div></div><button class="eventsNew" type="button" onclick="openEventForm()">+ Nuevo evento</button></div>'+eventForm()+renderCards()}
  window.openEventForm=()=>{let f=document.getElementById('eventForm');if(f){f.style.display='block';setTimeout(()=>document.getElementById('evName')?.focus(),30)}};
  window.closeEventForm=()=>{let f=document.getElementById('eventForm');if(f)f.style.display='none'};
  window.saveBasicEvent=()=>{let name=document.getElementById('evName').value.trim(),start=document.getElementById('evStart').value,end=document.getElementById('evEnd').value,brand=document.getElementById('evBrand').value.trim(),place=document.getElementById('evPlace').value.trim();if(!name||!start||!brand||!place){alert('Completa nombre, fecha, marca y local.');return}if(end&&end<start){alert('La fecha final no puede ser anterior a la inicial.');return}events.push({id:'ev-'+Date.now(),name,start,end:end||start,brand,place,staff:[],materials:[],notes:''});save()};
  window.renderEventsHome=renderEventsHome;renderEventsHome();
})();
