(()=>{
  const KEY='cp-events';let events=[],activeId=null;
  try{events=JSON.parse(localStorage.getItem(KEY)||'[]')||[]}catch(e){events=[]}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const today=()=>{let d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
  function save(){localStorage.setItem(KEY,JSON.stringify(events));renderEventsHome()}
  function eventForm(){return '<div id="eventForm" style="display:none;margin-top:16px;text-align:left;background:#f8fafc;border:1px solid #e4e7ec;border-radius:14px;padding:14px"><h3 style="margin:0 0 12px">Nuevo evento</h3><label style="font-size:12px;font-weight:800">Nombre / activación</label><input id="evName" placeholder="Ej. Degustación Parrilla Fest" style="width:100%;padding:10px;margin:5px 0 10px;border:1px solid #d0d5dd;border-radius:9px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:9px"><div><label style="font-size:12px;font-weight:800">Fecha inicio</label><input id="evStart" type="date" value="'+today()+'" style="width:100%;padding:10px;margin-top:5px;border:1px solid #d0d5dd;border-radius:9px"></div><div><label style="font-size:12px;font-weight:800">Fecha fin</label><input id="evEnd" type="date" value="'+today()+'" style="width:100%;padding:10px;margin-top:5px;border:1px solid #d0d5dd;border-radius:9px"></div></div><label style="display:block;font-size:12px;font-weight:800;margin-top:10px">Marca</label><input id="evBrand" placeholder="Marca" style="width:100%;padding:10px;margin:5px 0 10px;border:1px solid #d0d5dd;border-radius:9px"><label style="font-size:12px;font-weight:800">Local / lugar</label><input id="evPlace" placeholder="Local o lugar del evento" style="width:100%;padding:10px;margin:5px 0 12px;border:1px solid #d0d5dd;border-radius:9px"><div style="display:flex;gap:8px"><button type="button" onclick="closeEventForm()" style="flex:1;padding:10px;border:1px solid #d0d5dd;border-radius:9px;background:#fff;font-weight:800">Cancelar</button><button type="button" onclick="saveBasicEvent()" style="flex:1;padding:10px;border:0;border-radius:9px;background:#2563eb;color:#fff;font-weight:800">Guardar evento</button></div></div>'}
  function cards(){if(!events.length)return '<div class="eventsEmpty"><div class="eventsIcon">📅</div><strong>Aún no hay eventos registrados</strong><div class="muted">Crea el primer evento para comenzar su planificación.</div></div>';return '<div style="margin-top:16px;text-align:left">'+events.slice().sort((a,b)=>a.start.localeCompare(b.start)).map(e=>'<button type="button" onclick="openEventDetail(\''+e.id+'\')" style="display:block;width:100%;text-align:left;background:#fff;border:1px solid #e4e7ec;border-radius:13px;padding:13px;margin:8px 0;color:inherit"><div style="font-weight:850">'+esc(e.name)+'</div><div class="muted" style="margin-top:5px">📅 '+esc(e.start)+(e.end&&e.end!==e.start?' → '+esc(e.end):'')+'</div><div style="font-size:12px;margin-top:6px">🏷️ '+esc(e.brand)+' &nbsp; · &nbsp; 📍 '+esc(e.place)+'</div><div class="muted" style="margin-top:7px">👥 '+((e.staff||[]).length)+' turno(s) · Toca para abrir</div></button>').join('')+'</div>'}
  function staffRows(e){let roles=['Impulsadora','Logística','Supervisión'],all=(e.staff||[]).slice().sort((a,b)=>(a.date||e.start).localeCompare(b.date||e.start)||(a.start||'').localeCompare(b.start||''));if(!all.length)return '<div class="muted">Todavía no hay turnos asignados.</div>';return roles.map(role=>{let list=all.filter(p=>(p.role||'Impulsadora')===role);if(!list.length)return '';return '<div style="margin-top:13px"><div style="font-size:12px;font-weight:900;color:#475467;text-transform:uppercase">'+role+'</div>'+list.map(p=>'<div style="display:flex;justify-content:space-between;align-items:center;border:1px solid #e4e7ec;border-radius:10px;padding:10px;margin:6px 0"><div><strong>'+esc(p.name)+'</strong><div class="muted" style="margin-top:3px">📅 '+esc(p.date||e.start)+' &nbsp; 🕐 '+esc(p.start||'--:--')+' – '+esc(p.end||'--:--')+'</div></div><button onclick="removeEventStaffById(\''+esc(p.id||'')+'\')" style="border:0;background:#fff;color:#b42318;font-weight:800">Quitar</button></div>').join('')+'</div>'}).join('')}
  function detail(e){return '<div style="text-align:left"><button onclick="closeEventDetail()" style="border:0;background:transparent;font-weight:800;color:#2563eb;padding:0 0 12px">← Eventos</button><h2 style="margin:0">'+esc(e.name)+'</h2><div class="muted" style="margin:5px 0 4px">📅 '+esc(e.start)+(e.end!==e.start?' → '+esc(e.end):'')+'</div><div style="font-size:13px">🏷️ '+esc(e.brand)+' · 📍 '+esc(e.place)+'</div><div style="margin-top:20px;border-top:1px solid #e4e7ec;padding-top:15px"><h3 style="margin:0 0 10px">👥 Personal y turnos</h3><label style="font-size:11px;font-weight:800">Fecha del turno</label><input id="evStaffDate" type="date" min="'+esc(e.start)+'" max="'+esc(e.end)+'" value="'+esc(e.start)+'" style="width:100%;padding:10px;margin:4px 0 8px;border:1px solid #d0d5dd;border-radius:9px"><label style="font-size:11px;font-weight:800">Función</label><select id="evStaffRole" style="width:100%;padding:10px;margin:4px 0 8px;border:1px solid #d0d5dd;border-radius:9px;background:#fff"><option>Impulsadora</option><option>Logística</option><option>Supervisión</option></select><input id="evStaffName" placeholder="Nombre del personal" style="width:100%;padding:10px;margin-bottom:8px;border:1px solid #d0d5dd;border-radius:9px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><div><label style="font-size:11px;font-weight:800">Entrada</label><input id="evStaffIn" type="time" style="width:100%;padding:10px;margin-top:4px;border:1px solid #d0d5dd;border-radius:9px"></div><div><label style="font-size:11px;font-weight:800">Salida</label><input id="evStaffOut" type="time" style="width:100%;padding:10px;margin-top:4px;border:1px solid #d0d5dd;border-radius:9px"></div></div><button onclick="addEventStaff()" style="width:100%;margin-top:9px;padding:10px;border:0;border-radius:9px;background:#2563eb;color:#fff;font-weight:800">+ Agregar turno</button><div style="margin-top:12px">'+staffRows(e)+'</div></div></div>'}
  function renderEventsHome(){const box=document.getElementById('eventsModule');if(!box)return;if(activeId){let e=events.find(x=>x.id===activeId);if(e){box.innerHTML=detail(e);return}activeId=null}box.innerHTML='<div class="eventsHead"><div><h2>Eventos</h2><div class="muted">Planificación de activaciones, personal y materiales.</div></div><button class="eventsNew" type="button" onclick="openEventForm()">+ Nuevo evento</button></div>'+eventForm()+cards()}
  window.openEventForm=()=>{let f=document.getElementById('eventForm');if(f){f.style.display='block';setTimeout(()=>document.getElementById('evName')?.focus(),30)}};window.closeEventForm=()=>{let f=document.getElementById('eventForm');if(f)f.style.display='none'};
  window.saveBasicEvent=()=>{let name=document.getElementById('evName').value.trim(),start=document.getElementById('evStart').value,end=document.getElementById('evEnd').value,brand=document.getElementById('evBrand').value.trim(),place=document.getElementById('evPlace').value.trim();if(!name||!start||!brand||!place){alert('Completa nombre, fecha, marca y local.');return}if(end&&end<start){alert('La fecha final no puede ser anterior a la inicial.');return}events.push({id:'ev-'+Date.now(),name,start,end:end||start,brand,place,staff:[],materials:[],notes:''});save()};
  window.openEventDetail=id=>{activeId=id;renderEventsHome()};window.closeEventDetail=()=>{activeId=null;renderEventsHome()};
  window.addEventStaff=()=>{let e=events.find(x=>x.id===activeId);if(!e)return;let date=document.getElementById('evStaffDate').value,role=document.getElementById('evStaffRole').value,name=document.getElementById('evStaffName').value.trim(),start=document.getElementById('evStaffIn').value,end=document.getElementById('evStaffOut').value;if(!date||date<e.start||date>e.end){alert('Selecciona una fecha dentro del evento.');return}if(!name){alert('Escribe el nombre del personal.');return}if(!start||!end){alert('Indica horario de entrada y salida.');return}if(end<=start){alert('La hora de salida debe ser posterior a la entrada.');return}e.staff=e.staff||[];e.staff.push({id:'sh-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),date,role,name,start,end});save()};
  window.removeEventStaffById=id=>{let e=events.find(x=>x.id===activeId);if(!e)return;if(id)e.staff=e.staff.filter(p=>p.id!==id);else e.staff.pop();save()};
  window.renderEventsHome=renderEventsHome;renderEventsHome();
})();
