const logGet=id=>document.getElementById(id);
const logEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LOG_PAIRS=[
  {a:'impulsacion',aLabel:'Impulsación',c:'impulsadora',cLabel:'Impulsadora'},
  {a:'insumos',aLabel:'Insumos',c:'insumos',cLabel:'Insumos'},
  {a:'supervision',aLabel:'Supervisión',c:'supervisor',cLabel:'Supervisor'},
  {a:'logistica',aLabel:'Logística',c:'logistica',cLabel:'Logística'}
];
const LOG_DEFAULT={brands:[{id:'la-italiana',name:'LA ITALIANA',active:true}],stores:[]};
let logisticsConfig=(()=>{try{let x=JSON.parse(localStorage.getItem('cp-logistics-config')||'null');return x&&x.brands&&x.stores?x:JSON.parse(JSON.stringify(LOG_DEFAULT))}catch(e){return JSON.parse(JSON.stringify(LOG_DEFAULT))}})();
function saveLogistics(){localStorage.setItem('cp-logistics-config',JSON.stringify(logisticsConfig))}
function logTab(){renderLogistics()}
function logPairEnabled(s,p){if(s.activities&&typeof s.activities[p.a]==='boolean')return s.activities[p.a];if(s.categories&&typeof s.categories[p.c]==='boolean')return s.categories[p.c];return true}
function renderLogistics(){let view=logGet('logBrandsView');if(!view)return;view.innerHTML='<div class="logRow" style="margin-bottom:10px"><b>Marcas y locales</b><div style="display:flex;gap:6px"><button class="logAdd" onclick="addLogBrand()">+ Marca</button><button class="logAdd" onclick="addLogStore()">+ Local</button></div></div>'+logisticsConfig.brands.map(b=>{let stores=logisticsConfig.stores.filter(s=>s.brandId===b.id);return '<div class="logCard '+(b.active?'':'logInactive')+'" style="text-align:left"><div class="logRow" style="margin-bottom:8px"><div><div class="logTitle">🏷️ '+logEsc(b.name)+'</div><div class="logMeta">'+stores.length+' local(es)</div></div><div style="display:flex;gap:6px;align-items:center"><span class="logStatus '+(b.active?'':'off')+'">'+(b.active?'Activa':'Inactiva')+'</span><button class="logSmall" onclick="editLogBrand(\''+b.id+'\')">Editar</button></div></div><div style="display:grid;gap:7px">'+(stores.length?stores.map(s=>{let enabled=LOG_PAIRS.filter(p=>logPairEnabled(s,p));return '<div class="logCard '+(s.active?'':'logInactive')+'" style="margin:0;background:#f8fafc"><div class="logRow"><div><div class="logTitle">📍 '+logEsc(s.name)+'</div><div class="logMeta">'+logEsc(s.city||'GUAYAQUIL')+' · '+enabled.length+' tipo(s) habilitado(s)</div></div><div style="display:flex;gap:6px;align-items:center"><span class="logStatus '+(s.active?'':'off')+'">'+(s.active?'Activo':'Inactivo')+'</span><button class="logSmall" onclick="editLogStore(\''+s.id+'\')">Configurar</button></div></div></div>'}).join(''):'<div class="logMeta">No hay locales vinculados a esta marca.</div>')+'</div></div>'}).join('')}
function addLogBrand(){let name=prompt('Nombre de la nueva marca:');if(!name||!name.trim())return;let id='b-'+Date.now();logisticsConfig.brands.push({id,name:name.trim().toUpperCase(),active:true});saveLogistics();renderLogistics()}
function editLogBrand(id){let b=logisticsConfig.brands.find(x=>x.id===id);if(!b)return;let name=prompt('Nombre de la marca:',b.name);if(name&&name.trim())b.name=name.trim().toUpperCase();b.active=confirm('Aceptar = dejar ACTIVA\nCancelar = dejar INACTIVA');saveLogistics();renderLogistics()}
function addLogStore(){if(!logisticsConfig.brands.length){alert('Primero agrega una marca.');return}let name=prompt('Nombre del local:');if(!name||!name.trim())return;let city=prompt('Ciudad:','GUAYAQUIL');if(city===null)return;city=(city.trim()||'GUAYAQUIL').toUpperCase();let options=logisticsConfig.brands.map((b,i)=>(i+1)+'. '+b.name).join('\n');let n=parseInt(prompt('Marca del local:\n'+options,'1'))-1;if(!logisticsConfig.brands[n])return;let activities={},categories={};LOG_PAIRS.forEach(p=>{activities[p.a]=true;categories[p.c]=true});logisticsConfig.stores.push({id:'s-'+Date.now(),name:name.trim().toUpperCase(),city,brandId:logisticsConfig.brands[n].id,active:true,activities,categories});saveLogistics();renderLogistics()}
function editLogStore(id){let s=logisticsConfig.stores.find(x=>x.id===id);if(!s)return;let rows=LOG_PAIRS.map((p,i)=>'<div class="logToggle" style="display:grid;grid-template-columns:1fr auto 1fr auto;gap:8px;align-items:center"><div><div style="font-size:11px;color:#667085">ACTIVIDAD</div><b>'+p.aLabel+'</b></div><span style="color:#98a2b3">→</span><div><div style="font-size:11px;color:#667085">CATEGORÍA</div><b>'+p.cLabel+'</b></div><input type="checkbox" id="lp_'+i+'" '+(logPairEnabled(s,p)?'checked':'')+'></div>').join('');let html='<div class="modal" id="logStoreModal" style="display:flex" onclick="if(event.target===this)this.remove()"><div class="sheet logForm"><h3>Configurar '+logEsc(s.name)+'</h3><label>Nombre del local</label><input id="lsName" value="'+logEsc(s.name)+'"><label>Marca</label><select id="lsBrand">'+logisticsConfig.brands.map(b=>'<option value="'+b.id+'" '+(b.id===s.brandId?'selected':'')+'>'+logEsc(b.name)+'</option>').join('')+'</select><div class="logMeta" style="margin:4px 0 14px">Ciudad: '+logEsc(s.city||'GUAYAQUIL')+'</div><label>Actividad → Categoría</label><div class="muted" style="margin:3px 0 9px">Cada actividad queda vinculada a su categoría correspondiente.</div><div style="display:grid;gap:8px">'+rows+'</div><div class="logToggle" style="margin-top:12px"><label>Local activo</label><input type="checkbox" id="lsActive" '+(s.active?'checked':'')+'></div><div class="logActions" style="margin-top:12px"><button class="secondary" onclick="logGet(\'logStoreModal\').remove()">Cancelar</button><button class="primary" onclick="saveLogStore(\''+id+'\')">Guardar</button></div></div></div>';document.body.insertAdjacentHTML('beforeend',html)}
function saveLogStore(id){let s=logisticsConfig.stores.find(x=>x.id===id);if(!s)return;s.name=logGet('lsName').value.trim().toUpperCase()||s.name;s.brandId=logGet('lsBrand').value;s.active=logGet('lsActive').checked;s.activities=s.activities||{};s.categories=s.categories||{};LOG_PAIRS.forEach((p,i)=>{let on=logGet('lp_'+i).checked;s.activities[p.a]=on;s.categories[p.c]=on});saveLogistics();logGet('logStoreModal').remove();renderLogistics()}
